export const conditionToIcon: { [key: string]: string } = {
  'Sunny': '/icons/sunny-day.svg',
  'Clear': '/icons/clear-day.svg',
  'Partly Cloudy': '/icons/partly-cloudy-day.svg',
  'Partly cloudy': '/icons/partly-cloudy-night.svg',
  'Cloudy': '/icons/cloudy-day-1.svg',
  'Overcast': '/icons/cloudy.svg',
  'Mist': '/icons/rainy-4.svg',
  'Fog': '/icons/fog.svg',
  'Freezing fog': '/icons/fog.svg',
  'Patchy rain possible': '/icons/rainy-4.svg',
  'Patchy snow possible': '/icons/snow.svg',
  'Patchy sleet possible': '/icons/rain-and-sleet-mix.svg',
  'Patchy freezing drizzle possible': '/icons/rainy-1.svg',
  'Thundery outbreaks possible': '/icons/thunder.svg',
  'Blowing snow': '/icons/snow.svg',
  'Blizzard': '/icons/snowy-5.svg',
  'Patchy light drizzle': '/icons/rainy-1.svg',
  'Light drizzle': '/icons/rainy-1.svg',
  'Freezing drizzle': '/icons/rainy-1.svg',
  'Heavy freezing drizzle': '/icons/rainy-4.svg',
  'Patchy light rain': '/icons/rainy-1.svg',
  'Patchy rain nearby': '/icons/rainy-1.svg',
  'Light rain': '/icons/rainy-2.svg',
  'Moderate rain at times': '/icons/rainy-2.svg',
  'Moderate rain': '/icons/rainy-2.svg',
  'Heavy rain at times': '/icons/rainy-7.svg',
  'Heavy rain': '/icons/rainy-7.svg',
  'Light freezing rain': '/icons/rainy-1.svg',
  'Moderate or heavy freezing rain': '/icons/rainy-4.svg',
  'Light sleet': '/icons/rain-and-sleet-mix.svg',
  'Moderate or heavy sleet': '/icons/rain-and-sleet-mix.svg',
  'Patchy light snow': '/icons/snowy-1.svg',
  'Light snow': '/icons/snowy-2.svg',
  'Patchy moderate snow': '/icons/snowy-3.svg',
  'Moderate snow': '/icons/snowy-4.svg',
  'Patchy heavy snow': '/icons/snowy-5.svg',
  'Heavy snow': '/icons/snowy-5.svg',
  'Ice pellets': '/icons/snow.svg',
  'Light rain shower': '/icons/rainy-1-day.svg',
  'Moderate or heavy rain shower': '/icons/rainy-7.svg',
  'Torrential rain shower': '/icons/rainy-7.svg',
  'Light sleet showers': '/icons/rain-and-sleet-mix.svg',
  'Moderate or heavy sleet showers': '/icons/rain-and-sleet-mix.svg',
  'Light snow showers': '/icons/snowy-2.svg',
  'Moderate or heavy snow showers': '/icons/snowy-4.svg',
  'Light showers of ice pellets': '/icons/snow.svg',
  'Moderate or heavy showers of ice pellets': '/icons/snowy-5.svg',
  'Patchy light rain with thunder': '/icons/thunder.svg',
  'Moderate or heavy rain with thunder': '/icons/thunder.svg',
  'Thundery outbreaks in nearby': '/icons/thunder.svg',
  'Patchy light snow with thunder': '/icons/thunder.svg',
  'Moderate or heavy snow with thunder': '/icons/severe-thunderstorm.svg',
};
